# ======================================================
# 📘 Jupyter Book Configuration — Monique A. R. Mendoza
# Deep Learning Elective 4 | GitHub Pages Portfolio
# ======================================================

# Basic Book Information
title: "💜 Mendoza's Deep Learning Portfolio"
author: "Monique Antoinette R. Mendoza"
description: >
  A compilation of my Deep Learning laboratory activities and lecture tasks —
  showcasing both theory and practice through Jupyter Notebooks.

# Execution Configuration
execute:
  execute_notebooks: cache         # Cache notebooks for faster rebuilds
  allow_errors: true
  timeout: auto                    # Auto timeout (lets Jupyter Book decide)

# LaTeX / PDF Build Settings
latex:
  latex_documents:
    targetname: deep_learning_portfolio.tex

# References / Citations
bibtex_bibfiles:
  - references.bib

# GitHub Repository Info
repository:
  url: https://github.com/MoniqueMendoza/Deep-Learning-Elective-4.git
  path_to_book: DL_Mendoza
  branch: main

# HTML / Theme Settings
html:
  favicon: logo.png
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  home_page_in_navbar: true
  navbar_number_sections: false
  baseurl: ""
  extra_css:
    - _static/custom.css   # 💜 Connected dark purple theme
  extra_footer: |
    <p style="text-align:center; color:#e0b3ff;">
      © 2025 Monique Antoinette R. Mendoza — Deep Learning Portfolio
    </p>

# Exclude build folders and unnecessary files
exclude_patterns:
  - _build
  - Thumbs.db
  - .DS_Store
  - "**/.ipynb_checkpoints"

# Sphinx Theme & Behavior Settings
sphinx:
  config:
    html_theme_options:
      use_download_button: true
      navigation_with_keys: true
      show_navbar_depth: 2
      canonical_url: https://moniquemendoza.github.io/Deep-Learning-Elective-4